---
deployment:
  tasks:
    - export DEPLOYPATH=/home/zynk/solaraudit.online
    - /bin/cp -f index.html $DEPLOYPATH/
    - /bin/cp -f deploy.php $DEPLOYPATH/
    - /bin/cp -Rf css $DEPLOYPATH/
    - /bin/cp -Rf js $DEPLOYPATH/
